export const BASE_URL = "https://ladug.co.il/api/v1/test/challenges";

export const FETCH_CHALLENGES_REQUEST = 'FETCH_CHALLENGES_REQUEST';
export const FETCH_CHALLENGES_SUCCESS = 'FETCH_CHALLENGES_SUCCESS';
export const FETCH_CHALLENGES_FAILURE = 'FETCH_CHALLENGES_FAILURE';

export const FETCH_CHALLENGE_REQUEST = 'FETCH_CHALLENGE_REQUEST';
export const FETCH_CHALLENGE_SUCCESS = 'FETCH_CHALLENGE_SUCCESS';
export const FETCH_CHALLENGE_FAILURE = 'FETCH_CHALLENGE_FAILURE';

export const UPDATE_FAVOURITES = 'UPDATE_FAVOURITES';
